name: Win32/UWP build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    env:
      LD_DEBUG: all

    strategy:
      fail-fast: false
      matrix:
        name:            ["MinGW"]
        toolset:         ["x64"]
        build_type:      ["Release"]
        cmake_generator: ["MinGW Makefiles"]
        cmake_args:      ["-DDILIGENT_BUILD_CORE_TESTS=ON -DILIGENT_NO_DIRECT3D11=ON -DILIGENT_NO_DIRECT3D12=ON -DDILIGENT_NO_VULKAN=ON"]
        platform:        ["Win32"]

    name: Win10 -> ${{ matrix.name }}-${{ matrix.toolset }}, ${{ matrix.build_type }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Reinstall MinGW
      shell: pwsh
      run: |
        choco uninstall --yes --verbose mingw
        choco install --yes --verbose mingw --version=12.1.0

    - name: Set up build environment
      if: success()
      uses: DiligentGraphics/github-action/setup-build-env@v1
      with:
        platform:        ${{ matrix.platform }}
        cmake-generator: ${{ matrix.cmake_generator }}
        ninja-vs-arch:   ${{ matrix.toolset }}

    - name: Configure CMake
      if: success()
      uses: DiligentGraphics/github-action/configure-cmake@v1
      with:
        generator:  ${{ matrix.cmake_generator }}
        vs-arch:    ${{ matrix.toolset }}
        build-type: ${{ matrix.build_type }}
        cmake-args: ${{ matrix.cmake_args }}

    - name: Build
      id:   build
      if:   success()
      uses: DiligentGraphics/github-action/build@v1
      with:
        target: install

    - name: DiligentCoreTest
      if:   ${{ success() && matrix.name != 'UWP'}}
      uses: DiligentGraphics/github-action/run-core-tests@mingw

    - name: DiligentCoreAPITest D3D11
      # NB: it is essential to include failure() to override the default status check of success()
      #     that is automatically applied to if conditions that don't contain a status check function.
      if:   ${{ (success() || failure() && steps.build.outcome == 'success') && (matrix.name == 'Win10' || matrix.name == 'Win8.1') }}
      uses: DiligentGraphics/github-action/run-core-gpu-tests@v1
      with:
        mode: d3d11_sw

    - name: DiligentCoreAPITest D3D12
      if:   ${{ (success() || failure() && steps.build.outcome == 'success') && matrix.name == 'Win10' }}
      uses: DiligentGraphics/github-action/run-core-gpu-tests@v1
      with:
        mode: d3d12_sw

    - name: DiligentCoreAPITest D3D12 DXC
      if:   ${{ (success() || failure() && steps.build.outcome == 'success') && matrix.name == 'Win10' }}
      uses: DiligentGraphics/github-action/run-core-gpu-tests@v1
      with:
        mode:    d3d12_sw
        use-dxc: true
        # Disable texture creation tests that are not relevant for DXC to save time
        args: --gtest_filter=-TextureCreation*

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ success() && matrix.build_type != 'Debug' && matrix.cmake_generator != 'Ninja' }}
      with:
        name: DiligentCore-${{ matrix.name }}-${{ matrix.toolset }}-${{ matrix.build_type }}
        path: |
          ${{env.DILIGENT_INSTALL_DIR}}
          !${{env.DILIGENT_INSTALL_DIR}}/**/*.lib
          !${{env.DILIGENT_INSTALL_DIR}}/**/*.a
        retention-days: 90
